# Generated by Django 6.0 on 2025-12-11 08:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the workout session', max_length=200)),
                ('workout_type', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength Training'), ('flexibility', 'Flexibility/Yoga'), ('sports', 'Sports'), ('mixed', 'Mixed Training'), ('other', 'Other')], default='mixed', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes (1-600 minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)])),
                ('calories_burned', models.PositiveIntegerField(default=0, help_text='Estimated calories burned (0-5000)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the workout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fitness_workouts',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(help_text='Name of the exercise', max_length=200)),
                ('category', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core/Abs'), ('cardio', 'Cardio'), ('full_body', 'Full Body'), ('other', 'Other')], default='other', max_length=20)),
                ('sets', models.PositiveIntegerField(help_text='Number of sets (1-50)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('reps', models.PositiveIntegerField(help_text='Number of repetitions per set (1-1000)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('weight', models.FloatField(default=0.0, help_text='Weight used in kg (0-1000 kg, 0 for bodyweight)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('rest_time', models.PositiveIntegerField(default=60, help_text='Rest time between sets in seconds (0-600 seconds)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the exercise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness_tracker.workout')),
            ],
            options={
                'db_table': 'fitness_exercises',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(help_text='Age must be between 13 and 120 years', validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)])),
                ('weight', models.FloatField(help_text='Weight in kg (30-500 kg)', validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(500.0)])),
                ('height', models.FloatField(help_text='Height in cm (100-250 cm)', validators=[django.core.validators.MinValueValidator(100.0), django.core.validators.MaxValueValidator(250.0)])),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('lightly_active', 'Lightly Active (light exercise 1-3 days/week)'), ('moderately_active', 'Moderately Active (moderate exercise 3-5 days/week)'), ('very_active', 'Very Active (hard exercise 6-7 days/week)'), ('extremely_active', 'Extremely Active (very hard exercise, physical job)')], default='sedentary', max_length=20)),
                ('fitness_goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_muscle', 'Gain Muscle'), ('maintain_weight', 'Maintain Weight'), ('improve_endurance', 'Improve Endurance'), ('general_fitness', 'General Fitness')], default='general_fitness', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fitness_user_profiles',
                'indexes': [models.Index(fields=['user'], name='user_profile_user_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'date'], name='workout_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['workout_type'], name='workout_type_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['workout'], name='exercise_workout_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['category'], name='exercise_category_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['exercise_name'], name='exercise_name_idx'),
        ),
    ]
